### ISSUE TITLE
npm run server not working

### ISSUE THREAD

**Issue by taptapdan** [PERTS/triton#37]
Hi Chris. Trying to get triton up and running. What I did was...

- cloned down repo
- `npm install` (this also runs the `postinstall` so my git hooks are set)
- `npm run server`

This results in the following error:

```
09:49 $ npm run server

> triton@0.0.1 server /Users/fiore/code/perts/triton
> dev_appserver.py $(pwd) --port=10080 --admin_port=10008

Traceback (most recent call last):
  File "/usr/local/bin/dev_appserver.py", line 89, in <module>
    _run_file(__file__, globals())
  File "/usr/local/bin/dev_appserver.py", line 85, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1040, in <module>
    main()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1033, in main
    dev_server.start(options)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 758, in start
    options.config_paths, options.app_id)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 813, in __init__
    config_paths = self._config_files_from_paths(config_paths)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 879, in _config_files_from_paths
    self._config_files_from_dir(path) if os.path.isdir(path) else [path])
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 910, in _config_files_from_dir
    (dir_path, or_web_inf))
google.appengine.tools.devappserver2.errors.AppConfigNotFoundError: "/Users/fiore/code/perts/triton" is a directory but does not contain app.yaml or app.yml
```

Remembering that branch changes require a checkout, I attempted to `git checkout` to see if that would generate the needed files, but that results in the following:

```
09:49 $ git checkout
Neptune post-checkout hook running...
/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'gae_server/branch_environment.py': [Errno 2] No such file or directory
```

No README, so not sure what I'm missing. Thanks!

**Comment by taptapdan** [comment]
I noticed you're gone starting tomorrow. I'm happy to hop on hangouts today if it'd help work through the issue, that way maybe I can get React into the repo in between working on neptune dashboard.

**Comment by taptapdan** [comment]
```
git submodule update --init --recursive
add 'triton' user to mysql
```

**Comment by taptapdan** [comment]
Thanks, will add information to README.
