### ISSUE TITLE
Unable to log into triton

### ISSUE THREAD

**Issue by taptapdan** [PERTS/triton#39]
Leaving a note here as reminder to help me work through getting the repo as it currently stands working. We diagnosed getting triton running on Wednesday, so I'm able to access at http://localhost:10080 and see the login page. Neptune also needs to be run, so I grabbed the latest `master` and have that running.

But attempting to login with `admin@perts.net` results in Neptune returning a 500 with `"credentials_invalid"` as the response.

So, thinking that maybe `admin@perts.net` isn't allowed from triton to neptune for some reason, I attempted to use the Register functionality. When I enter an email, I see the link in terminal, so I copy paste that into browser. That brings me to the User Details page. Not sure what I'm supposed to put into that field. I attempted password. But I get the following error

```
ERROR    2017-07-07 21:40:50,155 api.py:51] 'email'
Traceback (most recent call last):
  File "/Users/fiore/code/perts/neptune/gae_server/gae_handlers/api.py", line 41, in dispatch
    BaseHandler.dispatch(self)
  File "/Users/fiore/code/perts/neptune/gae_server/gae_handlers/base.py", line 61, in dispatch
    user = self.get_current_user()
  File "/Users/fiore/code/perts/neptune/gae_server/gae_handlers/base.py", line 104, in get_current_user
    jwt_user = self.get_jwt_user()
  File "/Users/fiore/code/perts/neptune/gae_server/gae_handlers/base.py", line 158, in get_jwt_user
    user = User.create(id=short_uid)
  File "/Users/fiore/code/perts/neptune/app/model/user.py", line 110, in create
    is_unique_email = Unique.create(User.uniqueness_key(kwargs['email']))
KeyError: 'email'

INFO     2017-07-07 21:40:50,158 module.py:788] default: "POST /api/set_password HTTP/1.1" 500 783
```

So I'm stuck since I'm not sure of the process here.

**Comment by taptapdan** [comment]
Nevermind. Not sure what happened here, but I poked at it and it started working.
